#!/usr/bin/env ruby
require 'rubygems'
require 'daemons'
require 'mimic'

LOG_PATH = File.expand_path(File.join(File.dirname(__FILE__), *%w[.. log mimicd.log]))

# this needs to be an absolute path so it still works when the process is daemonized
STUB_FILE = File.expand_path(File.join(File.dirname(__FILE__), *%w[.. Tests Stubs mimic.rb]))

Daemons.run_proc("mimic") do
  Mimic.mimic(:port => 11988, :log => File.new(LOG_PATH, "w+"), :fork => false, :remote_configuration_path => "/api") do
    import(STUB_FILE)
  end
end
